<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="66501" started-at="2019-04-06T11:57:17Z" finished-at="2019-04-06T11:58:24Z">
    <groups>
    </groups>
    <test name="Insurance Search" duration-ms="66501" started-at="2019-04-06T11:57:17Z" finished-at="2019-04-06T11:58:24Z">
      <class name="com.vwfsinsuranceportal.com.vwfsinsuranceportal.insurancecheck.FindInsurance">
        <test-method status="PASS" signature="reportSetUp()[pri:0, instance:com.vwfsinsuranceportal.com.vwfsinsuranceportal.insurancecheck.FindInsurance@4cf777e8]" name="reportSetUp" is-config="true" duration-ms="503" started-at="2019-04-06T12:57:17Z" finished-at="2019-04-06T12:57:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportSetUp -->
        <test-method status="PASS" signature="setupTestEnvironment(java.lang.String, java.lang.String)[pri:0, instance:com.vwfsinsuranceportal.com.vwfsinsuranceportal.insurancecheck.FindInsurance@4cf777e8]" name="setupTestEnvironment" is-config="true" duration-ms="4573" started-at="2019-04-06T12:57:18Z" finished-at="2019-04-06T12:57:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://covercheck.vwfsinsuranceportal.co.uk/]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupTestEnvironment -->
        <test-method status="FAIL" signature="findInsurance()[pri:0, instance:com.vwfsinsuranceportal.com.vwfsinsuranceportal.insurancecheck.FindInsurance@4cf777e8]" name="findInsurance" duration-ms="60840" started-at="2019-04-06T12:57:22Z" finished-at="2019-04-06T12:58:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertTrue(Assert.java:44)at org.testng.Assert.assertTrue(Assert.java:54)at com.vwfsinsuranceportal.com.vwfsinsuranceportal.insurancecheck.FindInsurance.findInsurance(FindInsurance.java:21)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- findInsurance -->
        <test-method status="PASS" signature="endExtentReport(org.testng.ITestResult)[pri:0, instance:com.vwfsinsuranceportal.com.vwfsinsuranceportal.insurancecheck.FindInsurance@4cf777e8]" name="endExtentReport" is-config="true" duration-ms="178" started-at="2019-04-06T12:58:23Z" finished-at="2019-04-06T12:58:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=findInsurance status=FAILURE method=FindInsurance.findInsurance()[pri:0, instance:com.vwfsinsuranceportal.com.vwfsinsuranceportal.insurancecheck.FindInsurance@4cf777e8] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endExtentReport -->
        <test-method status="PASS" signature="endReport()[pri:0, instance:com.vwfsinsuranceportal.com.vwfsinsuranceportal.insurancecheck.FindInsurance@4cf777e8]" name="endReport" is-config="true" duration-ms="386" started-at="2019-04-06T12:58:23Z" finished-at="2019-04-06T12:58:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- com.vwfsinsuranceportal.com.vwfsinsuranceportal.insurancecheck.FindInsurance -->
    </test> <!-- Insurance Search -->
  </suite> <!-- Suite -->
</testng-results>
